Htmlandcss
gonzaloalonzo/setupandmobilefirst pull request #1
Opened 2023-03-24 12:23 UTC by gonzaloalonzo

creating pull request for the review

2023-03-24 12:28 UTC, Gambit142 reviewed
Hi @gonzaloalonzo 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that:

1. Not all the linters checks passed 
2. The pull request title is not good and doesn't reflect the changes made in the branch
3. The pull request summary is not descriptive. The pull request summary should describe changes that were introduced in this branch or features that were implemented. 👍 😎 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-24 13:39 UTC, Felix45 requested changes
Hi @gonzaloalonzo , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: 

You have submitted a project, that has the following issues
 
- The title of the pull request is not descriptive, it does not inform someone looking at the pull request what the pull request is about. A good title for this pull request would be something like `Milestone 1: Portfolio: setup and mobile first`. Please rectify this.
 
- The summary of the pull request is not descriptive. A good pull request summary should describe the changes that were introduced in this branch. I think it would be better if you listed all the features you worked on in the pull request summary.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-24 13:54 UTC, gonzaloalonzo commented
Don't understand this (A good pull request summary should describe the changes that were introduced in this branch)

2023-03-24 14:05 UTC, souad988 reviewed
Hi @gonzaloalonzo , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a good PR title as html and css are technologies that will be used in all steps of this project the title should describe the feature or bloc of work done in this milestone the summary you used for this PR is very short but meaningful it can be used as a title and then in the summary describe in few points the work exp: Add header with logo and hamberger button , Add headlines .... 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-24 14:07 UTC, ABDULALI3468 reviewed
Hi @gonzaloalonzo , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴

## Problems and their solutions:-

Please consider adding a professional title and description of your PR which describes what you have done in the Pull Request (PR). In this case, it's not describing it clearly.

>   ![pull_request_desc](https://user-images.githubusercontent.com/52934128/177452738-0610c008-a53a-454e-8aac-635cb4ed812c.gif)

> Title can be following:- **Milestone 1: Portfolio: setup and mobile-first**



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-24 16:05 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @gonzaloalonzo   
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Good job setting up your first project at microverse 👍 , but   I think It would be better if you added a descriptive README referring to this [template](https://github.com/microverseinc/readme-template), as It would allow your work to look more professional. 

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment, so I can receive the notification or use Slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 16:05 UTC, iambenkis commented on index.html
> +        <i class="fas fa-bars"></i>
- [ ] Your logo looks good 👍  , but for  semantic reason, kindly use an `a` tag 👍

2023-03-24 16:05 UTC, iambenkis commented on index.html
> +      <article class="job">
- [ ] As a header of your page , kindly use  the `header` tag , 
- [ ] Noe that the header contains the site's title or logo (or both) and the main site navigation 👍 , kindly update that.

2023-03-24 16:05 UTC, iambenkis commented on index.html
> +      </section>
- [ ] Kindly use the `ul` and the `li` to this list of icons  for semantic reason 👍

2023-03-25 04:11 UTC, LionRouge1 reviewed
Hi @gonzaloalonzo  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have all the linters passed. Kindly make sure you fix all linters errors before submitting your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-25 11:56 UTC, merged

2023-03-25 12:21 UTC, MeqdamAlqudah reviewed
Hi @gonzaloalonzo 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/74744787/227717048-af0ac54a-2f6a-46e5-b6f5-13412363795d.png)

## Highlights 
:+1: design 
:+1: semantic tags

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._